words = [
    "autotune",
    "bidir",
    "chrt",
    "cpupower",
    "dcp",
    "dmesg",
    "dut",
    "dutlib",
    "ethertype",
    "ethtool",
    "ipv",
    "lldp",
    "mbps",
    "mdev",
    "mtu",
    "phy",
    "profinet",
    "replsession",
    "rta",
    "rtc",
    "rtt",
    "skb",
    "sysfs",
    "tsn",
    "tso",
    "txrx",
    "urandom",
    "usec",
    "vid",
    "xdp",
]
